[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.0"
  NODE_VERSION = "18"
  # Skip problematic gems during build
  BUNDLE_WITHOUT = "development:test"
  # Force bundler to use precompiled gems when available
  BUNDLE_FORCE_RUBY_PLATFORM = "false"

# Cache configuration for faster builds
[build.processing]
  skip_processing = false

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
