backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", default: "Food Safety Expert"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "affiliate_products"
    label: "Affiliate Products"
    files:
      - label: "Products List"
        name: "products"
        file: "_data/affiliate_products.yml"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Product Name", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Amazon ASIN", name: "asin", widget: "string"}
              - {label: "Categories", name: "categories", widget: "list"}
              - {label: "Priority", name: "priority", widget: "number", default: 1}

  - name: "food_questions"
    label: "Food Questions"
    files:
      - label: "Questions List"
        name: "questions"
        file: "_data/food_questions.yml"
        fields:
          - label: "Questions"
            name: "questions"
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "text"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Source", name: "source", widget: "string"}
